<?php

namespace AE\FollowMusclesBundle\Repository;

/**
 * MuscleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuscleRepository extends \Doctrine\ORM\EntityRepository
{
}
